### ISSUE TITLE
Configure repository as template?

### ISSUE THREAD

**Issue by drudge** [n8n-io/n8n-nodes-starter#28]
Hi there!

I was wondering if it made sense to enable the "Template repository" setting on this repository.

Template repositories let users generate new repositories with the same directory structure and files. [Learn more](https://docs.github.com/articles/creating-a-repository-from-a-template/).

I've enabled this to try it out on my fork https://github.com/drudge/n8n-nodes-starter if you'd like to see how it works.

Clone button changes:
![image](https://user-images.githubusercontent.com/72890/181365373-b861841b-bde9-4c67-95be-1ccfa9f6a0de.png)

Shows link to template for projects created with it:
![image](https://user-images.githubusercontent.com/72890/181365467-cd7fd134-b9da-4edf-ac69-d09aa69e932a.png)

**Comment by csuermann** [comment]
Hi @drudge, Thank you for the suggestion, which makes a lot of sense. I've toggled it on 😄
