### ISSUE TITLE
doc outdated

### ISSUE THREAD

**Issue by Noiirod** [n8n-io/n8n-nodes-starter#48]
Hello, 
I'm a junior dev and i'm trying to do the [build your node tutorial](https://docs.n8n.io/integrations/creating-nodes/build/declarative-style-node/?), but i'm having some problems with it. The doc is actually using `npm` but the repository i cloned from the tutorial force me to use `pnpm`, can you give me the good way to reproduce the tutorial with the right commands ?

Thank you by advance.

**Comment by Joffcom** [comment]
Hey @Noiirod,

I noticed the other day and I need to take a look into the changes. For the most part you can replace `npm` with `pnpm` and that should get you most of the way there.

**Comment by Noiirod** [comment]
Nevermind i forget to build 😅

**Comment by Joffcom** [comment]
Is it all good now?

**Comment by Noiirod** [comment]
Yes, thank you for your time
