### ISSUE TITLE
Couchbase vector store as community node

### ISSUE THREAD

**Issue by roadgoat19** [n8n-io/n8n-nodes-starter#51]
I'd like to implement Couchbase vector store as a community node. Do I follow the same process as I would to create a regular community app node to create a vector store? For reference, I'd like it to function similarly to the Qdrant/Supabase/Pinecone vector stores.

Thank you!

**Comment by Joffcom** [comment]
Hey @roadgoat19,

It is a similar process so for AI nodes you would need to follow how the AI nodes are created, The package and the publish process is the same though.
