### ISSUE TITLE
not gonna lie this seems like a whole setup to create a custom node.

### ISSUE THREAD

**Issue by Maki9009** [n8n-io/n8n-nodes-starter#53]
it would be great to be able to create custom nodes within n8n - like a way to have a terminal to install dependencies and then a code box that i can just enter my code lets say i got code from claude or chatgpt. and then i have a submit node button. 

because i want to create my own node for playwright and this seems a bit confusing for me... and claude ngl. 

but i dont mind getting help doing it this way i just dont understand the step by step process in a sense. so if anyone wants to help please let me know.

**Comment by Joffcom** [comment]
Hey @Maki9009,

We have created an internal ticket to look into this which we will be tracking as "GHC-328"

**Comment by Joffcom** [comment]
Hey @Maki9009 

This doesn't sound like a bug so I am going to have to close this but if you want some help I would recommend posting on our community support forum.

I would look at existing nodes to see how they sit together and maybe go through the node building tutorial first just to get a feel for how things sit together.
